function a2dMap = Continuum_VdA_getMap_NC(sPathMap,sFileNameMap,sVarName)
%{

    Function reading 'sVarName' field in gzipped netcdf file generated by Continuum

%}

sFileNameGZ = [sPathMap,sFileNameMap];
sFileNameNC = sFileNameGZ(1:end-3);

gunzip(sFileNameGZ)

a2dMap = ncread(sFileNameNC,sVarName);
a2dMap = flipud(transpose(a2dMap));

delete(sFileNameNC)       